### ISSUE TITLE
Download links died

### ISSUE THREAD

**Issue by JoeyAW** [DCxDemo/THPS2-Cumulative-Patch#63]
Hey, love your work, I’m waiting for my thps2 copy to come in the mail. Thps-mods went down recently though so some links aren’t accessible, like v4prev2. I was wondering if you have any other downloads. Also is there a smaller exe without the nocd crack?

**Comment by DCxDemo** [comment]
Missing files are backed up on Discord. I think this smaller exe was a crack from the very beginning, so probably not. 
this old article here mentions the smaller exe
```
This exe was released as a cd crack, but at first it was the only way most 
people could get the game to run on Windows 2000, after that it was the 
most hackable executable you could find for the game.
```
http://planettonyhawk.gamespy.com/View160a.html?view=thps2_faqs_guides.Detail&id=61

**Comment by JoeyAW** [comment]
Huh, that’s interesting. I wonder why San Francisco is such a problem, it’s not in THUGPRO either.On Sep 16, 2024, at 11:54, DCxDemo ***@***.***> wrote:﻿
Missing files are backed up on Discord. I think this smaller exe was a crack from the very beginning, so probably not.
this old article here mentions the smaller exe
This exe was released as a cd crack, but at first it was the only way most 
people could get the game to run on Windows 2000, after that it was the 
most hackable executable you could find for the game.

http://planettonyhawk.gamespy.com/View160a.html?view=thps2_faqs_guides.Detail&id=61

**Comment by DCxDemo** [comment]
it's unrelated. iirc psx sanfran requires a model that either wasnt included in th2 or was somehow bugged. also ironically it was literally too big, causing polygon overflow. this patch increases the limit, so it doesn't crash.

on thugpro they focused on levels that were reused in other games and streets never appeared in ps2 era games. so they would have to implement a full blown psx to thug2 converter just for a single level.

**Comment by JoeyAW** [comment]
Oh that totally makes sense now. I always wondered if that map was buggedOn Sep 16, 2024, at 13:58, DCxDemo ***@***.***> wrote:﻿
it's unrelated. iirc psx sanfran requires a model that either wasnt included in th2 or was somehow bugged. also ironically it was literally too big, causing polygon overflow. this patch increases the limit, so it doesn't crash.
on thugpro they focused on levels that were reused in other games and streets never appeared in ps2 era games. so they would have to implement a full blown psx to thug2 converter just for a single level.
